### ISSUE TITLE
Add App Tile Filter Template

### ISSUE THREAD

**Issue by daviddickgrcc** [jsmpros/PeopleCodeTemplates#1]
Suggesting that you add a template for the TileFilter App class
https://docs.oracle.com/cd/F44200_01/pt859pbr2/eng/pt/tprt/task_HidingOrDisplayingTilesUsingAnApplicationClass.html
`import PTGP_APPCLASS_TILE:API:TileAppFilter;

class ChangeClassNameToEventName extends PTGP_APPCLASS_TILE:API:TileAppFilter
   method IsTileVisible();
end-class;

method IsTileVisible
   /+ &cref as ApiObject +/
   /+ Returns Boolean +/
   /+ Extends/implements PTGP_APPCLASS_TILE:API:TileAppFilter.IsTileVisible +/
   
   /* Application-specific logic to hide or show a tile. */
   If    REM ** TODO: Implementation Code Goes here; Then
      Return True;
   Else
      Return False;
   End-If;
end-method;`

**Comment by jsmpros** [comment]
Resolved: https://github.com/jsmpros/PeopleCodeTemplates/blob/master/TileAppFilter.ppl

Thank you for the submission.
